### ISSUE TITLE
Issue with this commit

### ISSUE THREAD

**Issue by micky387** [ResurrectionRemix/android_build#15]
Hello. i have an build failed with this commit.
At the end, i have "ERROR: couldn't find ro.product.device in build.prop"
I dont use this flag because it was generate by framework at the init.
I use unified devices for 3 devices.
Look,i show at this :
https://github.com/micky387/android_device_samsung_tbltexx/blob/cm-13.0/init/init_tblte.cpp#L66

How can i skip this build failed ?
Thanks

**Comment by westcripp** [comment]
can you pull build repo and try again . should be fixed . let me know if it works
