### ISSUE TITLE
zerofltexx doesn't exist in the breakfast menu

### ISSUE THREAD

**Issue by Umeaboy** [ResurrectionRemix/android_build#31]
[Build error for zerofltexx.txt](https://github.com/ResurrectionRemix/android_build/files/1101038/Build.error.for.zerofltexx.txt)

**Comment by fgl27** [comment]
that is not demanding to build.

you need the trees (device kernel vendor) any extra that may be on the dependency.mk, then launch the device and start the build

something like this

	. build/envsetup.sh
	lunch PRODUCT_NAME-userdebug
	mka bacon

web search if you have a problem first, not need to open a issue for a simple things as this.

**Comment by Umeaboy** [comment]
That didn't work.

I seem to be missing some repos.

I had the same problem with building STOCK LineageOS as well.

/Kristoffer


Den 2017-06-26 kl. 18:34, skrev Felipe de Leon:

**Comment by akhilnarang** [comment]
The breakfast/lunch menu is populated with devices from LineageOS's hudson repo

You don't need it , you can just `breakfast zerofltexx` or `lunch lineage_zerofltexx-userdebug` and then `make`/`mka` `bacon`, or simply `brunch zerofltexx`
