### ISSUE TITLE
Build Failure (AUDIO_CHANNEL_IN_5POINT1)

### ISSUE THREAD

**Issue by sreehax** [ResurrectionRemix/android_build#44]
I tried to post this issue to [here](https://github.com/Suicide-Squirrel/issues_oreo) first, but I was told i should post with Resurrection Remix. This was the only place I could think of to report this. At first, I modified the source a little (removed lock screen passcode ripple effect, changed 4g indicator to lte indicator, disabled type 0 sms/silent ping, enabled sending type 0 sms). But, the build got the below error, then a minute later failed.
```
hardware/qcom/audio-caf/msm8994/policy_hal/AudioPolicyManager.cpp:2140:25: error: use of undeclared identifier 'AUDIO_CHANNEL_IN_5POINT1'; did you mean 'AUDIO_CHANNEL_OUT_5POINT1'?
                    if (AUDIO_CHANNEL_IN_5POINT1 == channelMask) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~
                        AUDIO_CHANNEL_OUT_5POINT1
system/media/audio/include/system/audio-base.h:187:5: note: 'AUDIO_CHANNEL_OUT_5POINT1' declared here
    AUDIO_CHANNEL_OUT_5POINT1 = 63u, // (((((OUT_FRONT_LEFT | OUT_FRONT_RIGHT) | OUT_FRONT_CENTER) | OUT_LOW_FREQUENCY) | OUT_BACK_LEFT) | OUT_BACK_RIGHT)
    ^
5 warnings and 1 error generated.

```
I thought it was a problem with my changes, so I hard reset my changes. Then, I retried the build, and it gave this same error. Here is the full terminal output from running mka (there may be more errors I did not see): [https://bpaste.net/show/d90f07e6be85](https://bpaste.net/show/d90f07e6be85). I am using Arch Linux, but i resolved errors due to this early on and built a working rom in the past.There may be other errors in the log i have posted.

**Comment by fgl27** [comment]
too old closing.
