### ISSUE TITLE
J7 pro (j7y17lte) Bug fix

### ISSUE THREAD

**Issue by voice5sur5** [ResurrectionRemix/android_build#46]
Installation Problem
Battery Life Problem
no Battery équilibrate profile 
Bluetooth headphone Problem
Wi-Fi Problem
Sim 2 sound and mic problem
Charging Problem
Data Problem
Performance Problem
App Problem crash 
Sound Problem low 
Random Reboot and random boot work
Problems If Nothing Works
custom kernel with balnaced scall cpu 2 minimum and max 8 core between 200mhz and 1.6ghz
random freeze system
no gps tweak for battery drain
screen call random psh screen bouton
Proximity sensor fix
no full screen caller by default 
enhance build.prop for more tweak 
enable SDcard fusion as internal storage 
FM radio not exist 
touch sensitivity problem
no permanaly keep alive app in to ram and cpu priority and affinity set

**Comment by fgl27** [comment]
too old closing.
