### ISSUE TITLE
kitkat2 not available

### ISSUE THREAD

**Issue by dumtara** [ResurrectionRemix/android_build#6]
https://github.com/ResurrectionRemix/android_build is available for kitkat1 but not for kitkat2.
You have removed kitkat1 from ResurrectionRemix/platform_manifest, only kitkat2 is now available.
So I request you to add kitkat2 for android_build.
Thanks

**Comment by westcripp** [comment]
kitkat branches are broken dont even try to build .

**Comment by dumtara** [comment]
Then I suggest to remove it from github. As downloading this much stuff, results in broken branch issue.
Thanks for info.
